name: VModifier
main: VModifier\VModifier
version: 1.0.0-beta
api: 3.0.0-ALPHA10

author: kenygamer
description: A PocketMine-MP plugin to change what is displayed to the player when /version is issued
